spring.application.name=analytics-service
server.port=${PORT:8083}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/agriconnect}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.schema=analytics_schema
spring.flyway.schemas=analytics_schema
spring.flyway.default-schema=analytics_schema
spring.flyway.create-schemas=true
jwt.secret=${JWT_SECRET}
core.url=${CORE_SERVICE_URL:http://localhost:8082}
management.endpoints.web.exposure.include=health,info
server.error.include-stacktrace=never
