package com.agriconnect.rescue;
import java.math.*;import java.util.*;import org.springframework.http.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.jdbc.support.GeneratedKeyHolder;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/rescue-registrations")class RescueRegistrationController{private final JdbcClient db;private final CropClient crop;RescueRegistrationController(JdbcClient d,CropClient c){db=d;crop=c;}private long uid(){return Long.parseLong(SecurityContextHolder.getContext().getAuthentication().getName());}private String sel(){return"select id,crop_batch_id as \"batchId\",rescue_point_id as \"rescuePointId\",admin_id as \"approvedBy\",status,submitted_at as \"submittedAt\",reviewed_at as \"approvedAt\" from rescue_registrations";}
 @GetMapping @PreAuthorize("hasRole('ADMIN')")Map<String,Object>all(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){var rows=db.sql(sel()+" order by id limit :s offset :o").param("s",size).param("o",page*size).query().listOfRows();long total=db.sql("select count(*) from rescue_registrations").query(Long.class).single();return Map.of("content",rows,"number",page,"size",size,"totalElements",total,"totalPages",(total+size-1)/size,"first",page==0,"last",(long)(page+1)*size>=total,"empty",rows.isEmpty());}
 @GetMapping("/my")@PreAuthorize("hasRole('FARMER')")List<Map<String,Object>>mine(){return db.sql(sel()+" where farmer_id=:f order by id").param("f",uid()).query().listOfRows();}
 @GetMapping("/{id}")Map<String,Object>one(@PathVariable long id){return db.sql(sel()+" where id=:id").param("id",id).query().listOfRows().stream().findFirst().orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"RESCUE_REGISTRATION_NOT_FOUND","Rescue registration not found"));}
 @PostMapping @PreAuthorize("hasRole('FARMER')")ResponseEntity<?>create(@RequestBody Map<String,Object>x){long batch=((Number)x.get("batchId")).longValue();Map<String,Object>b=crop.batch(batch);if(((Number)b.get("farmerId")).longValue()!=uid())throw new DomainException(HttpStatus.FORBIDDEN,"CROP_BATCH_OWNERSHIP_REQUIRED","Crop batch does not belong to the authenticated farmer");String status=String.valueOf(b.get("status"));if(!Set.of("pending","available").contains(status))throw new DomainException(HttpStatus.CONFLICT,"CROP_BATCH_NOT_ELIGIBLE","Crop batch is not eligible for rescue");var key=new GeneratedKeyHolder();db.sql("insert into rescue_registrations(crop_batch_id,farmer_id,rescue_point_id,quantity_snapshot,status)values(:b,:f,:p,:q,'PENDING')").param("b",batch).param("f",uid()).param("p",x.get("rescuePointId")).param("q",new BigDecimal(String.valueOf(b.get("currentQuantity")))).update(key,"id");return ResponseEntity.status(201).body(one(key.getKey().longValue()));}
 @PatchMapping("/{id}/approve")@PreAuthorize("hasRole('ADMIN')")Map<String,Object>approve(@PathVariable long id){return review(id,"APPROVED");}@PatchMapping("/{id}/reject")@PreAuthorize("hasRole('ADMIN')")Map<String,Object>reject(@PathVariable long id){return review(id,"REJECTED");}
 @Transactional Map<String,Object>review(long id,String target){Map<String,Object>old=one(id);if(!"PENDING".equals(old.get("status")))throw new DomainException(HttpStatus.CONFLICT,"RESCUE_REGISTRATION_ALREADY_PROCESSED","Registration has already been processed");db.sql("update rescue_registrations set status=:s,admin_id=:a,reviewed_at=now()where id=:id and status='PENDING'").param("s",target).param("a",uid()).param("id",id).update();db.sql("insert into rescue_status_history(registration_id,from_status,to_status,changed_by)values(:id,'PENDING',:s,:u)").param("id",id).param("s",target).param("u",uid()).update();return one(id);}}
