package com.agriconnect.crop;
import java.math.*; import java.util.*; import org.springframework.http.*; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*;
@RestController class CropBatchController { private final JdbcClient db; private final UserDirectoryClient users; CropBatchController(JdbcClient d,UserDirectoryClient users){db=d;this.users=users;} private long uid(){return Long.parseLong(SecurityContextHolder.getContext().getAuthentication().getName());}
 private String select(){return "select id,crop_id as \"cropId\",farmer_id as \"farmerId\",farmer_name as \"farmerName\",initial_quantity as \"initialQuantity\",available_quantity as \"currentQuantity\",available_quantity as \"availableQuantity\",reserved_quantity as \"reservedQuantity\",sold_quantity as \"soldQuantity\",unit_price as \"unitPrice\",unit,harvest_date as \"harvestDate\",expiry_date as \"expiryDate\",province,district,ward,address_detail as \"addressDetail\",status from crop_batches";}
 @GetMapping("/api/crop-batches") Map<String,Object> list(@RequestParam Map<String,String> q){int page=Integer.parseInt(q.getOrDefault("page","0")),size=Math.min(100,Integer.parseInt(q.getOrDefault("size","20")));var rows=enrich(db.sql(select()+" where status <> 'pending' order by id limit :s offset :o").param("s",size).param("o",page*size).query().listOfRows());long total=db.sql("select count(*) from crop_batches where status <> 'pending'").query(Long.class).single();return Map.of("content",rows,"number",page,"size",size,"totalElements",total,"totalPages",(total+size-1)/size,"first",page==0,"last",(long)(page+1)*size>=total,"empty",rows.isEmpty());}
 @GetMapping("/api/crop-batches/{id}") Map<String,Object> one(@PathVariable long id){return find(id);}
 @GetMapping("/api/crop-batches/my") @PreAuthorize("hasRole('FARMER')") Map<String,Object> mine(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){var rows=enrich(db.sql(select()+" where farmer_id=:f order by id limit :s offset :o").param("f",uid()).param("s",size).param("o",page*size).query().listOfRows());return Map.of("content",rows,"number",page,"size",size,"totalElements",rows.size(),"totalPages",rows.isEmpty()?0:1,"first",true,"last",true,"empty",rows.isEmpty());}
 @PostMapping("/api/crop-batches") @PreAuthorize("hasRole('FARMER')") ResponseEntity<?> create(@RequestBody Map<String,Object>x){BigDecimal initial=new BigDecimal(String.valueOf(x.get("initialQuantity")));var row=db.sql("insert into crop_batches(crop_id,farmer_id,initial_quantity,available_quantity,reserved_quantity,sold_quantity,unit_price,unit,harvest_date,expiry_date,province,district,ward,address_detail,status) values(:c,:f,:i,:i,0,0,:p,:u,:h,:e,:pr,:d,:w,:a,'pending') returning id").param("c",x.get("cropId")).param("f",uid()).param("i",initial).param("p",x.getOrDefault("unitPrice",0)).param("u",x.get("unit")).param("h",x.get("harvestDate")).param("e",x.get("expiryDate")).param("pr",x.get("province")).param("d",x.get("district")).param("w",x.get("ward")).param("a",x.get("addressDetail")).query().singleRow();return ResponseEntity.status(201).body(find(((Number)row.get("id")).longValue()));}
 @DeleteMapping("/api/crop-batches/{id}") @PreAuthorize("hasRole('FARMER')") ResponseEntity<Void> delete(@PathVariable long id){if(db.sql("delete from crop_batches where id=:id and farmer_id=:f").param("id",id).param("f",uid()).update()==0)throw new DomainException(HttpStatus.NOT_FOUND,"CROP_BATCH_NOT_FOUND","Crop batch not found");return ResponseEntity.noContent().build();}
 @GetMapping("/internal/crop-batches/{id}") Map<String,Object> internal(@PathVariable long id,@RequestHeader("X-Internal-Api-Key")String key,@org.springframework.beans.factory.annotation.Value("${internal.api-key}")String expected){if(!java.security.MessageDigest.isEqual(key.getBytes(),expected.getBytes()))throw new DomainException(HttpStatus.FORBIDDEN,"INVALID_INTERNAL_KEY","Invalid internal API key");return find(id);}
 private Map<String,Object> find(long id){var row=db.sql(select()+" where id=:id").param("id",id).query().listOfRows().stream().findFirst().orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"CROP_BATCH_NOT_FOUND","Crop batch not found"));return enrich(new ArrayList<>(List.of(row))).get(0);}
 private List<Map<String,Object>> enrich(List<Map<String,Object>> rows){var ids=rows.stream().map(r->((Number)r.get("farmerId")).longValue()).collect(java.util.stream.Collectors.toSet());var names=users.names(ids);rows.forEach(r->{if(r.get("farmerName")==null||String.valueOf(r.get("farmerName")).isBlank())r.put("farmerName",names.getOrDefault(((Number)r.get("farmerId")).longValue(),"Farmer #"+r.get("farmerId")));});return rows;}
}
