package com.agriconnect.crop;
import java.util.*; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/crops") class CropController { private final JdbcClient db; CropController(JdbcClient d){db=d;}
 @GetMapping List<Map<String,Object>> all(){return db.sql("select id,name,description,storage_days as \"storageDays\",default_unit as \"defaultUnit\" from crops order by id").query().listOfRows();}
 @GetMapping("/{id}") Map<String,Object> one(@PathVariable long id){return db.sql("select id,name,description,storage_days as \"storageDays\",default_unit as \"defaultUnit\" from crops where id=:id").param("id",id).query().listOfRows().stream().findFirst().orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"CROP_NOT_FOUND","Crop not found"));}
 @PostMapping @PreAuthorize("hasRole('ADMIN')") ResponseEntity<?> create(@RequestBody Map<String,Object> x){var row=db.sql("insert into crops(name,description,storage_days,default_unit) values(:n,:d,:s,:u) returning id").param("n",x.get("name")).param("d",x.get("description")).param("s",x.get("storageDays")).param("u",x.get("defaultUnit")).query().singleRow();return ResponseEntity.status(201).body(one(((Number)row.get("id")).longValue()));}
 @RequestMapping(value="/{id}",method={RequestMethod.PUT,RequestMethod.PATCH}) @PreAuthorize("hasRole('ADMIN')") Map<String,Object> update(@PathVariable long id,@RequestBody Map<String,Object>x){one(id);db.sql("update crops set name=:n,description=:d,storage_days=:s,default_unit=:u,updated_at=now() where id=:id").param("n",x.get("name")).param("d",x.get("description")).param("s",x.get("storageDays")).param("u",x.get("defaultUnit")).param("id",id).update();return one(id);}
 @DeleteMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") ResponseEntity<Void> delete(@PathVariable long id){one(id);db.sql("delete from crops where id=:id").param("id",id).update();return ResponseEntity.noContent().build();}
}
