/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments.index'
import { Route as RescueIndexRouteImport } from './routes/rescue.index'
import { Route as RescuePointsIndexRouteImport } from './routes/rescue-points.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as CoordinationIndexRouteImport } from './routes/coordination.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CartIndexRouteImport } from './routes/cart.index'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RescueIdRouteImport } from './routes/rescue.$id'
import { Route as RescuePointsIdRouteImport } from './routes/rescue-points.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as FarmerRescueRequestsRouteImport } from './routes/farmer.rescue-requests'
import { Route as FarmerBatchesRouteImport } from './routes/farmer.batches'
import { Route as CategoriesIdRouteImport } from './routes/categories.$id'
import { Route as AdminSubsidyRouteImport } from './routes/admin.subsidy'
import { Route as AdminRescueRequestsRouteImport } from './routes/admin.rescue-requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueIndexRoute = RescueIndexRouteImport.update({
  id: '/rescue/',
  path: '/rescue/',
  getParentRoute: () => rootRouteImport,
} as any)
const RescuePointsIndexRoute = RescuePointsIndexRouteImport.update({
  id: '/rescue-points/',
  path: '/rescue-points/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinationIndexRoute = CoordinationIndexRouteImport.update({
  id: '/coordination/',
  path: '/coordination/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueIdRoute = RescueIdRouteImport.update({
  id: '/rescue/$id',
  path: '/rescue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RescuePointsIdRoute = RescuePointsIdRouteImport.update({
  id: '/rescue-points/$id',
  path: '/rescue-points/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRescueRequestsRoute = FarmerRescueRequestsRouteImport.update({
  id: '/farmer/rescue-requests',
  path: '/farmer/rescue-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerBatchesRoute = FarmerBatchesRouteImport.update({
  id: '/farmer/batches',
  path: '/farmer/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubsidyRoute = AdminSubsidyRouteImport.update({
  id: '/admin/subsidy',
  path: '/admin/subsidy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRescueRequestsRoute = AdminRescueRequestsRouteImport.update({
  id: '/admin/rescue-requests',
  path: '/admin/rescue-requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/rescue-requests': typeof AdminRescueRequestsRoute
  '/admin/subsidy': typeof AdminSubsidyRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/farmer/batches': typeof FarmerBatchesRoute
  '/farmer/rescue-requests': typeof FarmerRescueRequestsRoute
  '/products/$id': typeof ProductsIdRoute
  '/rescue-points/$id': typeof RescuePointsIdRoute
  '/rescue/$id': typeof RescueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/coordination/': typeof CoordinationIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rescue-points/': typeof RescuePointsIndexRoute
  '/rescue/': typeof RescueIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/rescue-requests': typeof AdminRescueRequestsRoute
  '/admin/subsidy': typeof AdminSubsidyRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/farmer/batches': typeof FarmerBatchesRoute
  '/farmer/rescue-requests': typeof FarmerRescueRequestsRoute
  '/products/$id': typeof ProductsIdRoute
  '/rescue-points/$id': typeof RescuePointsIdRoute
  '/rescue/$id': typeof RescueIdRoute
  '/admin': typeof AdminIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/cart': typeof CartIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/coordination': typeof CoordinationIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/rescue-points': typeof RescuePointsIndexRoute
  '/rescue': typeof RescueIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/rescue-requests': typeof AdminRescueRequestsRoute
  '/admin/subsidy': typeof AdminSubsidyRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/farmer/batches': typeof FarmerBatchesRoute
  '/farmer/rescue-requests': typeof FarmerRescueRequestsRoute
  '/products/$id': typeof ProductsIdRoute
  '/rescue-points/$id': typeof RescuePointsIdRoute
  '/rescue/$id': typeof RescueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/coordination/': typeof CoordinationIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/rescue-points/': typeof RescuePointsIndexRoute
  '/rescue/': typeof RescueIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/rescue-requests'
    | '/admin/subsidy'
    | '/categories/$id'
    | '/farmer/batches'
    | '/farmer/rescue-requests'
    | '/products/$id'
    | '/rescue-points/$id'
    | '/rescue/$id'
    | '/admin/'
    | '/analytics/'
    | '/buyer/'
    | '/cart/'
    | '/categories/'
    | '/checkout/'
    | '/coordination/'
    | '/farmer/'
    | '/orders/'
    | '/products/'
    | '/rescue-points/'
    | '/rescue/'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/rescue-requests'
    | '/admin/subsidy'
    | '/categories/$id'
    | '/farmer/batches'
    | '/farmer/rescue-requests'
    | '/products/$id'
    | '/rescue-points/$id'
    | '/rescue/$id'
    | '/admin'
    | '/analytics'
    | '/buyer'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/coordination'
    | '/farmer'
    | '/orders'
    | '/products'
    | '/rescue-points'
    | '/rescue'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/admin/rescue-requests'
    | '/admin/subsidy'
    | '/categories/$id'
    | '/farmer/batches'
    | '/farmer/rescue-requests'
    | '/products/$id'
    | '/rescue-points/$id'
    | '/rescue/$id'
    | '/admin/'
    | '/analytics/'
    | '/buyer/'
    | '/cart/'
    | '/categories/'
    | '/checkout/'
    | '/coordination/'
    | '/farmer/'
    | '/orders/'
    | '/products/'
    | '/rescue-points/'
    | '/rescue/'
    | '/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRescueRequestsRoute: typeof AdminRescueRequestsRoute
  AdminSubsidyRoute: typeof AdminSubsidyRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  FarmerBatchesRoute: typeof FarmerBatchesRoute
  FarmerRescueRequestsRoute: typeof FarmerRescueRequestsRoute
  ProductsIdRoute: typeof ProductsIdRoute
  RescuePointsIdRoute: typeof RescuePointsIdRoute
  RescueIdRoute: typeof RescueIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CoordinationIndexRoute: typeof CoordinationIndexRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RescuePointsIndexRoute: typeof RescuePointsIndexRoute
  RescueIndexRoute: typeof RescueIndexRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue/': {
      id: '/rescue/'
      path: '/rescue'
      fullPath: '/rescue/'
      preLoaderRoute: typeof RescueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue-points/': {
      id: '/rescue-points/'
      path: '/rescue-points'
      fullPath: '/rescue-points/'
      preLoaderRoute: typeof RescuePointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordination/': {
      id: '/coordination/'
      path: '/coordination'
      fullPath: '/coordination/'
      preLoaderRoute: typeof CoordinationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue/$id': {
      id: '/rescue/$id'
      path: '/rescue/$id'
      fullPath: '/rescue/$id'
      preLoaderRoute: typeof RescueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue-points/$id': {
      id: '/rescue-points/$id'
      path: '/rescue-points/$id'
      fullPath: '/rescue-points/$id'
      preLoaderRoute: typeof RescuePointsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/rescue-requests': {
      id: '/farmer/rescue-requests'
      path: '/farmer/rescue-requests'
      fullPath: '/farmer/rescue-requests'
      preLoaderRoute: typeof FarmerRescueRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/batches': {
      id: '/farmer/batches'
      path: '/farmer/batches'
      fullPath: '/farmer/batches'
      preLoaderRoute: typeof FarmerBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subsidy': {
      id: '/admin/subsidy'
      path: '/admin/subsidy'
      fullPath: '/admin/subsidy'
      preLoaderRoute: typeof AdminSubsidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rescue-requests': {
      id: '/admin/rescue-requests'
      path: '/admin/rescue-requests'
      fullPath: '/admin/rescue-requests'
      preLoaderRoute: typeof AdminRescueRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRescueRequestsRoute: AdminRescueRequestsRoute,
  AdminSubsidyRoute: AdminSubsidyRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  FarmerBatchesRoute: FarmerBatchesRoute,
  FarmerRescueRequestsRoute: FarmerRescueRequestsRoute,
  ProductsIdRoute: ProductsIdRoute,
  RescuePointsIdRoute: RescuePointsIdRoute,
  RescueIdRoute: RescueIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CoordinationIndexRoute: CoordinationIndexRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RescuePointsIndexRoute: RescuePointsIndexRoute,
  RescueIndexRoute: RescueIndexRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
